"""add audit trail columns to bilag

Revision ID: 440b7bc07a62
Revises: 4f0820497a19
Create Date: 2026-03-27 21:51:23.844704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '440b7bc07a62'
down_revision: Union[str, None] = '4f0820497a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('reconciled_by_user', sa.UUID(), nullable=True))
    op.add_column('bank_transactions', sa.Column('private_marked_by_user', sa.UUID(), nullable=True))
    op.add_column('bilag', sa.Column('created_by_user', sa.UUID(), nullable=True))
    op.add_column('bilag', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('bilag', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bilag', sa.Column('posted_by', sa.UUID(), nullable=True))
    op.add_column('cluster_data_points', sa.Column('confirmed_by', sa.UUID(), nullable=True))
    op.add_column('cluster_data_points', sa.Column('overridden_by', sa.UUID(), nullable=True))
    op.alter_column('cluster_data_points', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('cluster_data_points', 'overridden_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('employees', 'tax_card_fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('invoices', sa.Column('created_by_user', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('sent_by', sa.UUID(), nullable=True))
    op.alter_column('payslips', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payslips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('posteringer', sa.Column('created_by_user', sa.UUID(), nullable=True))
    op.add_column('system_users', sa.Column('track', sa.Enum('LONN', 'MVA', name='authorizationtrack'), nullable=False))
    op.create_index(op.f('ix_system_users_track'), 'system_users', ['track'], unique=False)
    op.create_unique_constraint('uq_system_user_org_track', 'system_users', ['customer_org_number', 'track'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_system_user_org_track', 'system_users', type_='unique')
    op.drop_index(op.f('ix_system_users_track'), table_name='system_users')
    op.drop_column('system_users', 'track')
    op.drop_column('posteringer', 'created_by_user')
    op.alter_column('payslips', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('payslips', 'paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('invoices', 'sent_by')
    op.drop_column('invoices', 'created_by_user')
    op.alter_column('employees', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('employees', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('employees', 'tax_card_fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cluster_data_points', 'overridden_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cluster_data_points', 'confirmed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('cluster_data_points', 'overridden_by')
    op.drop_column('cluster_data_points', 'confirmed_by')
    op.drop_column('bilag', 'posted_by')
    op.drop_column('bilag', 'approved_at')
    op.drop_column('bilag', 'approved_by')
    op.drop_column('bilag', 'created_by_user')
    op.drop_column('bank_transactions', 'private_marked_by_user')
    op.drop_column('bank_transactions', 'reconciled_by_user')
    # ### end Alembic commands ###
