"""add rejection_summaries to companies

Revision ID: 451faab39d10
Revises: 8ac31ac1633f
Create Date: 2026-03-28 00:23:07.777530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '451faab39d10'
down_revision: Union[str, None] = '8ac31ac1633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rejection_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rejection_summaries')
    # ### end Alembic commands ###
