"""add_periodisering_suggestion_to_bilag

Revision ID: 4f0820497a19
Revises: 78c8bc90aa7a
Create Date: 2026-03-26 08:33:58.462420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0820497a19'
down_revision: Union[str, None] = '78c8bc90aa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bilag', sa.Column('periodisering_suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('employees', 'pay_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pay_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.drop_column('bilag', 'periodisering_suggestion')
    # ### end Alembic commands ###
