"""add_retention_metadata_amelding_audit_hold

Revision ID: 78c8bc90aa7a
Revises: 
Create Date: 2026-03-25 20:45:48.401869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c8bc90aa7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('bank_transactions', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('bank_transactions', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bank_transactions', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bank_transactions_fiscal_year'), 'bank_transactions', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_bank_transactions_retention_expires_at'), 'bank_transactions', ['retention_expires_at'], unique=False)
    op.add_column('bilag', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('bilag', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('bilag', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('bilag', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bilag', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bilag_fiscal_year'), 'bilag', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_bilag_retention_expires_at'), 'bilag', ['retention_expires_at'], unique=False)
    op.add_column('companies', sa.Column('audit_hold_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('companies', sa.Column('audit_hold_reason', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('audit_hold_activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('audit_hold_activated_by', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('employees', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_employees_fiscal_year'), 'employees', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_employees_retention_expires_at'), 'employees', ['retention_expires_at'], unique=False)
    op.add_column('invoices', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('invoices', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoices_fiscal_year'), 'invoices', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_invoices_retention_expires_at'), 'invoices', ['retention_expires_at'], unique=False)
    op.add_column('payslips', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('payslips', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('payslips', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('payslips', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payslips', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payslips_fiscal_year'), 'payslips', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_payslips_retention_expires_at'), 'payslips', ['retention_expires_at'], unique=False)
    op.add_column('posteringer', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('posteringer', sa.Column('retention_category', sa.String(length=50), nullable=True))
    op.add_column('posteringer', sa.Column('retention_expires_at', sa.Date(), nullable=True))
    op.add_column('posteringer', sa.Column('audit_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('posteringer', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posteringer_fiscal_year'), 'posteringer', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_posteringer_retention_expires_at'), 'posteringer', ['retention_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posteringer_retention_expires_at'), table_name='posteringer')
    op.drop_index(op.f('ix_posteringer_fiscal_year'), table_name='posteringer')
    op.drop_column('posteringer', 'purged_at')
    op.drop_column('posteringer', 'audit_hold')
    op.drop_column('posteringer', 'retention_expires_at')
    op.drop_column('posteringer', 'retention_category')
    op.drop_column('posteringer', 'fiscal_year')
    op.drop_index(op.f('ix_payslips_retention_expires_at'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_fiscal_year'), table_name='payslips')
    op.drop_column('payslips', 'purged_at')
    op.drop_column('payslips', 'audit_hold')
    op.drop_column('payslips', 'retention_expires_at')
    op.drop_column('payslips', 'retention_category')
    op.drop_column('payslips', 'fiscal_year')
    op.drop_index(op.f('ix_invoices_retention_expires_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fiscal_year'), table_name='invoices')
    op.drop_column('invoices', 'purged_at')
    op.drop_column('invoices', 'audit_hold')
    op.drop_column('invoices', 'retention_expires_at')
    op.drop_column('invoices', 'retention_category')
    op.drop_column('invoices', 'fiscal_year')
    op.drop_index(op.f('ix_employees_retention_expires_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_fiscal_year'), table_name='employees')
    op.drop_column('employees', 'purged_at')
    op.drop_column('employees', 'audit_hold')
    op.drop_column('employees', 'retention_expires_at')
    op.drop_column('employees', 'retention_category')
    op.drop_column('employees', 'fiscal_year')
    op.drop_column('companies', 'audit_hold_activated_by')
    op.drop_column('companies', 'audit_hold_activated_at')
    op.drop_column('companies', 'audit_hold_reason')
    op.drop_column('companies', 'audit_hold_active')
    op.drop_index(op.f('ix_bilag_retention_expires_at'), table_name='bilag')
    op.drop_index(op.f('ix_bilag_fiscal_year'), table_name='bilag')
    op.drop_column('bilag', 'purged_at')
    op.drop_column('bilag', 'audit_hold')
    op.drop_column('bilag', 'retention_expires_at')
    op.drop_column('bilag', 'retention_category')
    op.drop_column('bilag', 'fiscal_year')
    op.drop_index(op.f('ix_bank_transactions_retention_expires_at'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_fiscal_year'), table_name='bank_transactions')
    op.drop_column('bank_transactions', 'purged_at')
    op.drop_column('bank_transactions', 'audit_hold')
    op.drop_column('bank_transactions', 'retention_expires_at')
    op.drop_column('bank_transactions', 'retention_category')
    op.drop_column('bank_transactions', 'fiscal_year')
    # ### end Alembic commands ###
