"""add source_rule_id and override feedback fields

Revision ID: 8ac31ac1633f
Revises: 440b7bc07a62
Create Date: 2026-03-27 23:47:06.875619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac31ac1633f'
down_revision: Union[str, None] = '440b7bc07a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bilag', sa.Column('source_rule_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bilag', 'reconciliation_rules', ['source_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bilag', type_='foreignkey')
    op.drop_column('bilag', 'source_rule_id')
    # ### end Alembic commands ###
